console.log("--- Advanced Array Methods ---");

let arr = ["A", "B", "C"];
let mapped = arr.map((val, idx) => val + idx);
console.log("Map with index:", mapped); // [A0, B1, C2]

let numbers = [1, 2, 3, 4];
// Testing reduce with an initial value and index
let sum = numbers.reduce((acc, curr, idx) => acc + curr + idx, 0);
console.log("Reduce with index:", sum); // (1+0) + (2+1) + (3+2) + (4+3) = 16

// Testing array mutation with splice
let spliceTest = [10, 20, 30, 40, 50];
let removed = spliceTest.splice(1, 2, 99, 100); 
console.log("Splice mutated array:", spliceTest); // [10, 99, 100, 40, 50]
console.log("Splice removed elements:", removed); // [20, 30]

// Testing find and findIndex
console.log("Find > 20:", spliceTest.find(n => n > 20)); // 99
console.log("FindIndex > 20:", spliceTest.findIndex(n => n > 20)); // 1


console.log("--- Scopes & Closures ---");

// Testing closures inside loops (the classic let vs var behavior)
let funcs = [];
for (let i = 0; i < 3; i++) {
    funcs.push(() => i);
}
console.log("Closure loop 0:", funcs[0]()); // 0
console.log("Closure loop 1:", funcs[1]()); // 1
console.log("Closure loop 2:", funcs[2]()); // 2

// Testing scope shadowing
let x = "global";
function outer() {
    let x = "outer";
    function inner() {
        let x = "inner";
        console.log("Inside inner:", x); // inner
    }
    inner();
    console.log("Inside outer:", x); // outer
}
outer();
console.log("Global x:", x); // global


console.log("--- Advanced Destructuring ---");

// Nested Object Destructuring
let user = { profile: { name: "Alice", zip: 12345 } };
let { profile: { name: uName, zip } } = user;
console.log("Nested object:", uName, zip); // Alice 12345

// Array Elision (skipping slots) and Rest
let [first, , third, ...rest] = [10, 20, 30, 40, 50];
console.log("Array elision & rest:", first, third, rest); // 10 30 [40, 50]

// Destructuring in function parameters with defaults
function connect({ host = "localhost", port = 8080 } = {}) {
    console.log(`Connecting to ${host}:${port}`);
}
connect({ port: 3000 }); // Connecting to localhost:3000
connect();               // Connecting to localhost:8080


console.log("--- Error Handling ---");

function riskyProcess(val) {
    if (val < 0) {
        throw { name: "ValidationError", message: "Negative values not allowed" };
    }
    return val * 2;
}

try {
    console.log(riskyProcess(5)); // 10
    console.log(riskyProcess(-1)); // Will throw
    console.log("This line should never print");
} catch (err) {
    console.log("Caught Error Name:", err.name);       // ValidationError
    console.log("Caught Error Message:", err.message); // Negative values not allowed
} finally {
    console.log("Finally block always runs");
}

// Catching a ReferenceError generated by your Environment.java
try {
    console.log(thisVariableDoesNotExist);
} catch (e) {
    console.log("Caught Native Error:", e.name, e.message); 
}

console.log("--- Dates & Math built-ins ---");

let d = new Date();
console.log("Current Year > 2000?", d.getFullYear() > 2000); // true
console.log("Month is valid?", d.getMonth() >= 0 && d.getMonth() <= 11); // true

// ParseInt / ParseFloat
console.log("parseInt:", parseInt("42"));     // 42
console.log("parseFloat:", parseFloat("3.14")); // 3.14

// Type Conversion
console.log("String coercion:", String(false)); // "false"
console.log("Number coercion:", Number(" 100 ")); // 100
console.log("Boolean coercion:", Boolean("")); // false

// Math edge cases
console.log("Math.max with no args:", Math.max()); // -Infinity
console.log("Math.min with no args:", Math.min()); // Infinity

console.log("--- Proving 'WILL FAIL' tests actually WORK! ---");

// 1. String comparison (Parser -> evalBinaryOp line 397)
console.log("Is 'b' > 'a'?", "b" > "a"); // true

// 2. Nullish Coalescing (Parser -> parseNullish line 351)
console.log("Nullish 1:", null ?? "default fallback"); // default fallback
console.log("Nullish 2:", 0 ?? "default fallback");    // 0

// 3. instanceof (Interpreter -> evalBinaryOp line 407)
function Car(model) { this.model = model; }
let myCar = new Car("Toyota");
console.log("instanceof Car?", myCar instanceof Car); // true

// 4. Shorthand Object Properties (Parser -> parseObjectLiteral line 572)
let myX = 5, myY = 10;
let point = { myX, myY };
console.log("Shorthand Props:", point.myX, point.myY); // 5 10